### ISSUE TITLE
Possible causing Facebook app crash

### ISSUE THREAD

**Issue by zhuoyang** [sonyxperiadev/boringssl-compat#1]
https://gist.github.com/zhuoyang/44a037b933f35c5b0bcc

**Comment by erikcas** [comment]
see (quite a dated) article here: http://www.gadgethelpline.com/fix-found-for-app-crashing-in-android-m-preview/

google has shifted to a new ssl in Marshmallow. Appmakers should also shift to boringssl for their apps.

Bottomline is, Facebook app is not ready yet for M.

**Comment by humberos** [comment]
Fixed with latest changes.
